name: exsurgat
description: "GABC renderer for Flutter."
version: 0.1.0
repository: https://github.com/osoftware/exsurgat
homepage: https://github.com/osoftware/exsurgat
issue_tracker: https://github.com/osoftware/exsurgat/issues
topics:
  - gabc
  - gregorian-chant
  - music
  - engraving
  - rendering
funding:
  - https://buymeacoffee.com/ostudio
  - https://pay.e.cash/?bip21=ecash:qrx0l5a2cjg679pghc7kalc8ff7uczf58qu7n49rwa

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
